### ISSUE TITLE
замечания

### ISSUE THREAD

**Issue by demist** [lhjlbjyjd/TP#1]
+ нет описания архитектуры
+ нет схемы (в репозитории)
по схеме:
+ не ясно, где наследование, а где зависимость
+ зачем несколько фабрик (разных) для одной нации?

**Comment by smplio** [comment]
Превые три будет исправлено
Последний пункт обсудили на семинаре: Сделал так из за отсутствия знаний о паттерне "Декоратор"
Вы сказали, что окей, пусть будет.

**Comment by smplio** [comment]
Подтвердите исправление

**Comment by demist** [comment]
+ в описании архитектуры не хватает указания конкретных классов. То, что написано у вас - это описание геймплея, а не архитектуры игры как ПО.
+ схема ок

**Comment by smplio** [comment]
Готово (?)

**Comment by demist** [comment]
засчитано
